# Generated by Django 6.0.1 on 2026-01-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestShot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        help_text="Relative path in media volume", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingShot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.CharField(max_length=500)),
                (
                    "inferred_text",
                    models.CharField(
                        blank=True,
                        help_text="Text inferred by the model",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "actual_text",
                    models.CharField(
                        blank=True,
                        help_text="Corrected text provided by user",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "is_accurate",
                    models.BooleanField(
                        blank=True,
                        help_text="True if green checkmark, False if red X",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workflow_id",
                    models.CharField(
                        help_text="DBOS workflow ID that created this detection",
                        max_length=200,
                    ),
                ),
                ("image_path", models.CharField(max_length=500)),
                ("plate_text", models.CharField(blank=True, max_length=50, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("camera_model", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow_id"], name="core_detect_workflo_722b30_idx"
                    )
                ],
            },
        ),
    ]
